### ISSUE TITLE
Reduce Dependencies

### ISSUE THREAD

**Issue by tshauck** [wheretrue/biobear#109]
With the recent aligner addition, new dependencies (rust-bio) can burden the user to install/compile biobear. Obviously, we'd like to avoid that if possible. See https://github.com/wheretrue/biobear/issues/106.

**Comment by tshauck** [comment]
I think this is resolved at e.g. previously this took ~11 mins on ubuntu and is down to ~20 secs to install from pip:

* Prior: https://github.com/wheretrue/biobear/actions/runs/8366079345/job/22905443202
* Today: https://github.com/wheretrue/biobear/actions/runs/8380346075/job/22949360752

@abearab, not sure if you might be able to see if that helps on your end?

**Comment by abearab** [comment]
@tshauck I could also install the new version much faster now! Great job 💪

**Comment by tshauck** [comment]
@abearab Thanks for checking! Closing this issue.
