### ISSUE TITLE
Random subsampling of reads from BAM files

### ISSUE THREAD

**Issue by abearab** [wheretrue/biobear#110]
I'm trying something like this https://www.biostars.org/p/76791/

How can I do it using `biobear`?

I started from this
```python
session = bb.connect()

subsampling_seed=42
number_of_reads=50000

bam = session.sql(f"""
    SELECT *
    FROM bam_scan('{BAM}') bam
""")
```

Then I could also do this which is not exactly random selection
```python
bam = session.sql(f"""
    SELECT *
    FROM bam_scan('{BAM}') bam
    LIMIT {number_of_reads}
""")
```

Finally I'm trying this which is not exactly what I should do:
![image](https://github.com/wheretrue/biobear/assets/53412130/eeb19dfd-f8b5-4813-899d-14227d5c118b)

___
@tshauck – what do you think? Thanks for your helps!

**Comment by tshauck** [comment]
@abearab Hey, I think you were very close... could you try, `ORDER BY RANDOM()`, though I don't think you can set the seed if that's critical.

Also, I should make this clearer, but biobear leverages Apache DataFusion for general purpose SQL functions, standard joins, etc, and you can see info about which functions are available here: https://arrow.apache.org/datafusion/user-guide/sql/index.html (in addition to the specialized ones I've added like `reverse_complement`). E.g. the docs for [`random`](https://arrow.apache.org/datafusion/user-guide/sql/scalar_functions.html#random).

**Comment by abearab** [comment]
> @abearab Hey, I think you were very close... could you try, `ORDER BY RANDOM()`, though I don't think you can set the seed if that's critical.

I see, thanks for the correction. I just tried it and it's seems it's working now.

> Also, I should make this clearer, but biobear leverages Apache DataFusion for general purpose SQL functions, standard joins, etc, and you can see info about which functions are available here: https://arrow.apache.org/datafusion/user-guide/sql/index.html (in addition to the specialized ones I've added like `reverse_complement`). E.g. the docs for [`random`](https://arrow.apache.org/datafusion/user-guide/sql/scalar_functions.html#random).

Cool, I'll look into `datafusion` docs. Thanks

Two questions / comments: 
1. how can I write bam files after I made these kind of manipulation?
2. it took 20 minutes and it didn't finish [for 26G BAM file], should I just keep waiting or there is a faster way for this? I also tried `sambamba` with 10 cores but that also didn't finish after 20-30 minutes.
<img width="477" alt="image" src="https://github.com/wheretrue/biobear/assets/53412130/5c16e5d6-99f2-4535-87e6-3987ab16f60e">

**Comment by tshauck** [comment]
Regrettably one cannot write files yet. I need to finish supporting reading CRAM files, then the next major thing is supporting file output.

**Comment by abearab** [comment]
I think you answered my question here, I'm going to close this issue for now to cleanup your repo! Thanks

**Comment by tshauck** [comment]
Thanks!
