### ISSUE TITLE
Why is specifying the extension required when reading files?

### ISSUE THREAD

**Issue by ghuls** [wheretrue/biobear#152]
Why is specifying the extension required when reading files?

When the wrong one is specified, an empty dataframe is returned.

```python
In [41]: fasta = session.read_fasta_file("Ns.fa", options=bb.FASTAReadOptions()).to_polars()

In [42]: fasta
Out[42]: 
shape: (0, 3)
┌─────┬─────────────┬──────────┐
│ id  ┆ description ┆ sequence │
│ --- ┆ ---         ┆ ---      │
│ str ┆ str         ┆ str      │
╞═════╪═════════════╪══════════╡
└─────┴─────────────┴──────────┘

In [43]: fasta = session.read_fasta_file("Ns.fa", options=bb.FASTAReadOptions(file_extension="fa").to_polars()

In [44]: fasta
Out[44]: 
shape: (1, 3)
┌──────┬─────────────┬─────────────────────────────────┐
│ id   ┆ description ┆ sequence                        │
│ ---  ┆ ---         ┆ ---                             │
│ str  ┆ str         ┆ str                             │
╞══════╪═════════════╪═════════════════════════════════╡
│ chr1 ┆ null        ┆ NNNNNNNNNNNNNNNNNNNNNNNNNNNNNN… │
└──────┴─────────────┴─────────────────────────────────┘

In [47]: fasta = session.read_fasta_file("/home/luna.kuleuven.be/u0079808/Downloads/Ns.fa", options=bb.FASTAReadOptions(file_extension="fasta",)).to_polars()

In [48]: fasta
Out[48]: 
shape: (0, 3)
┌─────┬─────────────┬──────────┐
│ id  ┆ description ┆ sequence │
│ --- ┆ ---         ┆ ---      │
│ str ┆ str         ┆ str      │
╞═════╪═════════════╪══════════╡
└─────┴─────────────┴──────────┘
```

It would be nice if the extension and compression would be automatically be detected by checking the extension(s) if not explicitly set.

Also at the moment: `fasta_sequence_data_type` option can't be set as `FastaSequenceDataType` is not exposed.

**Comment by tshauck** [comment]
Thanks for bringing this up... it's setup to potentially treat many files as one table (e.g. a directory of FASTAs), which is why if you're not using `.fasta` it needs to be specified. But you're right that can/should be improved to automatically detect in the single file case.

I'll look into it this afternoon and try to resolve at least for FASTA files (along w/ compression).

**Comment by tshauck** [comment]
This should work now for FASTA and FASTQ, except for the last one example in that if the user explicitly passes an option for which extension to use biobear will respect that. I've made #154 to continue to make file path options inferable ordered in rough priority. If there's a particular one you're interested in, happy to do that first. Thanks again for raising this!
