### ISSUE TITLE
Can not read ".fq" file

### ISSUE THREAD

**Issue by xiasijian** [wheretrue/biobear#163]
![image](https://github.com/user-attachments/assets/3718ebcc-52c7-40e6-9b61-919f3cbbed21)

**Comment by xiasijian** [comment]
![image](https://github.com/user-attachments/assets/020bda97-0526-47ad-9872-b58421480c23)
maybe you can update it, thanks.

**Comment by tshauck** [comment]
Hi @xiasijian, sorry that's giving you issues. Can you try using `read_fastq_file` on the session context. It should be able to infer the file extension. See https://github.com/wheretrue/biobear/blob/8d4f8f19174631a79f431cbed6cb37b9818f9a38/python/tests/test_session.py#L143-L158 for the test case.

**Comment by tshauck** [comment]
@xiasijian I'm gonna close this, but feel free to reopen if `read_fastq_file` doesn't work for you.

**Comment by xiasijian** [comment]
![image](https://github.com/user-attachments/assets/313df1d5-2b80-4c8d-a8eb-7cf0d886345c)
It is OK, Thanks a lot~
