### ISSUE TITLE
Wheels for Python 3.13?

### ISSUE THREAD

**Issue by jkanche** [wheretrue/biobear#188]
Hi @tshauck, wondering if you ran into this before. I am running into an issue installing biobear for 3.13. Seems like the wheels are not available so it tries to build from source. incase it helps: https://github.com/BiocPy/GenomicRanges/actions/runs/12437261937/job/34726750214?pr=133

**Comment by tshauck** [comment]
@jkanche Hey, thanks for the note. I need to do a little work to get biobear + exon on Python 3.13. Will try to get it done over the next few days and follow up. Thanks for raising this!

**Comment by jkanche** [comment]
no worries, thank you for your help.

**Comment by tshauck** [comment]
@jkanche wheels should now be build for 3.13. I'm a little uncertain about 3.13t, because it's not fully support by PyO3 yet, but 3.13 looks to work fine. Please lmk if it gives you any issues. Thanks!
