### ISSUE TITLE
Conda-forge package?

### ISSUE THREAD

**Issue by Hoeze** [wheretrue/biobear#44]
Hi, are there any plans to publish this library on conda-forge?

**Comment by tshauck** [comment]
Hey, yeah, something I've wanted to do, but wasn't sure where I should prioritize it relative to other stuff. I'll have a look today -- hopefully won't be too bad 🤞 

Out of curiosity, is the pip route causing you problems, or do you just prefer the conda ecosystem?

**Comment by Hoeze** [comment]
Hi @tshauck, thanks a lot for the quick reaction! :+1: 

To your question:
Shipping pip-packages in production quickly gets very messy.

With pure conda packages, I run into way less broken dependency issues:
Pip tends to cause problems when you do not add their package dependencies to your conda environment explicitly.
For example, when one library in your conda environment requires "scipy<=5" but your package requires "scipy>5", pip would just overwrite packages no matter what other libraries require.
Conda would instead try to resolve all dependencies.

So yes, I prefer if all my dependencies are on conda(-forge).

**Comment by tshauck** [comment]
Open PR for conda forge here: https://github.com/conda-forge/staged-recipes/pull/23350

**Comment by tshauck** [comment]
Hi @Hoeze ... just wanted to follow up that biobear is now on conda forge... see https://anaconda.org/conda-forge/biobear for conda forge and https://github.com/wheretrue/biobear/actions/runs/5638278478 for the smoke-test.

I'm going to close this, but please reopen if you have any issues.

**Comment by Hoeze** [comment]
Amazing! Thanks a lot @tshauck :smile:
