### ISSUE TITLE
Bam file loading functionality

### ISSUE THREAD

**Issue by jdcla** [wheretrue/biobear#60]
Loading and sending data from a bam file to a polars dataframe can take up to an hour for larger files. Often times, not all columns are necessary for downstream processing.  Having the option to only load a select number of columns would not only reduce computation time, but also memory consumption.

**Comment by tshauck** [comment]
Thanks for filing an issue... I actually recently added projection pushdown for BAM files in [Exon](https://github.com/wheretrue/exon/blob/4f620f91e8f6879379d78a5acd786982f68f61d2/exon/src/datasources/bam/array_builder.rs#L100-L214), so I'll expose that through biobear in the next few days.

Also... w.r.t. performance are you using a region on an indexed bam or only scanning a larger BAM? Either way if you have an example dataset/query, it'd be great to validate w/e changes I make would work for you.

**Comment by jdcla** [comment]
Sounds great. I'm currently working on sensitive data so nothing I can share. I'm happy to report differences on loading time for my example. For my case, I need to load in all entries in the bam file, but only have need of few columns.  Using polars on a sam file, it looks like this, a solution that is surprisingly performant.

```python
  df = pl.read_csv(
      path,
      has_header=False,
      comment_char="@",
      columns=[2, 3, 9],
      sep="\t",
      low_memory=low_memory,
  )
```

**Comment by tshauck** [comment]
Hi @jdcla, apologies for the delay. There was a snafu I had to work through related to pypi.

You should be able to install an updated version with support for projection pushdowns. Here's an example of loading all the contents from a BAM file. This is a 10x Genomics BAM file that has about 125,000,000 records.

```python
import biobear as bb

fpath = "/path/to/file/CytAssist_FFPE_Human_Colon_Rep2_possorted_genome_bam.bam"
s = f"CREATE EXTERNAL TABLE test STORED AS BAM LOCATION '{fpath}'"

ctx = bb.connect()

ctx.sql(s)

# show the table schema
results = ctx.sql("DESCRIBE test")
df = results.to_polars()
print(df)

results = ctx.sql('SELECT reference, start, "end" FROM test')
df = results.to_polars()
```

**Comment by jdcla** [comment]
Hey @tshauck, pulled in the update and evaluated the new functionality. Thanks a ton for following up on this.

This suits my needs, loading is five times slower as compared to directly loading a sam file using polars (~30s vs. ~2:30min), but this is expected. 

No feedback from me atm. Thank you for your work on biobear. The ease of conversion to e.g., polars, speed compared to other tools, usability as shown here and biobear being a lightweight package are all great.

I'm good with closing the issue, but I'll leave that decision up to you.

**Comment by tshauck** [comment]
Ok great, glad it's going to workout for your use-case. I'll close this ticket since your unblocked, but I do think/hope there's more speed that can be had. Hopefully future releases will see more improvements.

**Comment by tshauck** [comment]
Hi @jdcla, I feel a little weird asking, but would you be ok if I used part of your comment as a sort of "review"? -- attributed or anonymous, whichever you want? Something like:

> The ease of conversion to e.g., polars, speed compared to other tools, usability as shown here and biobear being a lightweight package are all great features.

**Comment by jdcla** [comment]
Go ahead, you can attribute it to me or anonymous.
