### ISSUE TITLE
Deprecation points to non-existent docs

### ISSUE THREAD

**Issue by jguhlin** [wheretrue/biobear#84]
```
DeprecationWarning: FastaReader is being deprecated, please use a table function via the session.
See https://www.wheretrue.dev/docs/exon/exondb/api-reference/table-functions for more info.
```

That link leads to a "Page Not Found" error

Generated from this code:
```
bb.FastaReader(seqfile).to_arrow()
```
(So not using exon)

**Comment by jguhlin** [comment]
Cheers. It does seem like a lot of extra complexity to just to get a basic
iterator, but that is just my opinion.

**Comment by tshauck** [comment]
Cool, yeah, I got a bit of a wild hair, but agree and'll probably leave them in.

**Comment by jguhlin** [comment]
Very relatable
